@startuml

class User {
  +int id
  +string email
  +string password
  +Role role
  +Date dateJoined
}

class Resource {
  +int id
  +string title
  +string description
  +string url
  +Category category
  +Date createdAt
  +Date updatedAt
  +User createdBy
}

class Post {
  +int id
  +string title
  +string content
  +string image
  +Date createdAt
  +Date updatedAt
  +User createdBy
}

class Event {
  +int id
  +string description
  +Date eventDate
  +User createdBy
}

enum Role {
  Admin
  Member
}

enum Category {
  Link
  Document
}

enum Tag {
  Web dev
  Data science
  AI
  DevOps
}

User "1" -- "0..*" Resource : creates >
User "1" -- "0..*" Post : writes >
User "1" -- "0..*" Event : organizes >
Resource "0..*" -- "1" Category : belongs to >
Post "0..*" -- "0..*" Tag : tagged >
User "0..*" -- "1" Role : has >

@enduml