@startuml name Website Use Case Diagram


actor Visitor
actor Member
actor Admin

Visitor <|-d- Member
Member <|-d- Admin

note left of Member
A Member can be: 
- 1st Year
- 2nd Year
- 3rd Year
- 4th Year
- Alumni
end note

rectangle "Website" {
  
}

@enduml