const semesters = [
    { id: 1, label: '1st Semester', content: `Algorithms and Data Structures,
  Computers Architecture,
  Statistics and Applied Probability,
  Operational Research Elements,
  Business, Ethics, and Difficulty,
  Administration, Economics, and Finance I,
  Languages, Communication, and Personal development I` },
    { id: 2, label: '2nd Semester', content: `Database,
  Systems and Networks,
  Computer Fundamentals,
  Software Development and Object-Oriented Programming,
  Federative Project 1Y,
  Economy, Management, and Finance II,
  Language, Dommunication, and Personal Development II` },
    { id: 3, label: '3rd Semester', content: `Information System,
  Compilation and Theory of Languages,
  Object Software Engineering,
  TCP/IP model and Distributed Dystems,
  Data Analysis and statistics,
  Cloud Computing & Virtualization,
  Entrepreneurial Culture,
  Communication and Languages III` },
    { id: 4, label: '4th Semester', content: `IT Project Management,
  Database Administration,
  Software Industrialization,
  AI concepts and Technologies,
  Decision-making systems,
  Mobile Applications and Architecture,
  End of Second Year Project,
  Communication and Languages IV` },
    { id: 5, label: '5th Semester', content: `Enterprise Application Integration,
  Big Data Ecosystem,
  Spatial Databases,
  IMDM Option’s Federative Project,
  Multimedia Data Integration, Storage, Research, and
  Analysis,
  Advanced Software Architectures,
  IS Governance,
  IT Management,
  Information System Quality,
  Big Data Analysis And Knowledge Extraction,
  Openings And Technological Conferences,
  ILSI Option’s Federative Project,
  Communication and Languages V` },
    { id: 6, label: '6th Semester', content: `End of Studies' Project` }
  ];
export default semesters;