@startuml

title Sequence diagram - Signup

actor Visitor as vis
participant AuthService as auth
participant EmailService as email
actor Admin as admin
database DB as db

vis -> auth: Signup request
auth -->> vis: Signup form

vis ->> auth: Personal info + credential
auth ->> db: Store user info
auth ->> email: Send user info
email ->> admin: Notify of new signup request

admin ->> auth: Validate signup request

auth -> db: Update account status (active)
db ->> auth: User info

vis <-- auth: Signup successful
  
@enduml