@startuml
start

:Upload list of Teams (T);
:Upload list of Subjects (S);

:Initialize list of Assignments (A);

while (T is not empty?) is (yes)
    :Display available teams from T;
    :Randomly select a team t from T;

    :Display available subjects from S;

    :Team t chooses a subject s from the displayed subjects;

    :Remove s from S;
    :Remove t from T;
    :Add (t, s) to A;
    :Display list of Assignments (A);
endwhile (no)

:Export list of Assignments (A);

stop
@enduml